### ISSUE TITLE
Working with Replicates

### ISSUE THREAD

**Issue by gremame** [nucleosome-dynamics/NucDyn#4]
Hello everyone,
I have been using NucDyn lately. Both, using the individual functions in this library as well as the Nucleosome Dynamics CLI. So far obtaining great results. Up until this point I have been using BAM files from individual samples for each condition.
However, I now wanted to ask for your advice in an scenario where I'm working with multiple sample replicates for each condition (ie more than one BAM per condition). I would like to obtain per condition results (not per sample). What would be the best way to approach this analysis? One of the possibilities I'm considering is either merging the BAMs (or the GenomicRanges objects) for each condition. However, think this could be a too simplistic approach. How would you recommend addressing this study?
Thanks in advance!

**Comment by lcodo** [comment]
Hi,
The approach you propose could be feasible. However if your bam files are
too big it might cause some memory issues.
A second approach could be to run the algorithm for pairs of samples and
then keep only the results obtained in all the comparisons, as a sort of
validation among replicates.
We hope this helps. Please let us know if this works for you.

Best regards,

**Comment by gremame** [comment]
Thank you for your reply Laia!
